"""Initial schema

Revision ID: e5239f6fc1aa
Revises: 
Create Date: 2026-07-07 16:25:19.659412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'e5239f6fc1aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # op.create_index('idx_cities_boundary', 'cities', ['boundary'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_cities_slug'), 'cities', ['slug'], unique=True)
    op.create_table('zones',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('zone_type', sa.String(length=50), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_zones_boundary', 'zones', ['boundary'], unique=False, postgresql_using='gist')
    # op.create_index('idx_zones_centroid', 'zones', ['centroid'], unique=False, postgresql_using='gist')
    op.create_index('ix_zones_search_vector', 'zones', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_zones_slug'), 'zones', ['slug'], unique=False)
    op.create_table('city_summaries',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('mood', sa.String(length=20), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=False),
    sa.Column('mood_emoji', sa.String(length=10), nullable=False),
    sa.Column('data_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trending_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_city_summaries_city_generated', 'city_summaries', ['city_id', 'generated_at'], unique=False)
    op.create_table('events',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_events_location', 'events', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_events_search_vector', 'events', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('news_articles',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('importance_score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_news_articles_location', 'news_articles', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_news_articles_content_hash'), 'news_articles', ['content_hash'], unique=True)
    op.create_index('ix_news_city_published', 'news_articles', ['city_id', 'published_at'], unique=False)
    op.create_index('ix_news_search_vector', 'news_articles', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('social_mentions',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('post_id', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('engagement_score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'post_id', name='uq_social_mention_platform_post')
    )
    op.create_index('ix_social_mentions_search_vector', 'social_mentions', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('traffic_data',
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('road_name', sa.String(length=300), nullable=True),
    sa.Column('current_speed', sa.Float(), nullable=False),
    sa.Column('free_flow_speed', sa.Float(), nullable=False),
    sa.Column('congestion_level', sa.String(length=20), server_default=sa.text("'free_flow'"), nullable=False),
    sa.Column('incidents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=100), server_default=sa.text("'tomtom'"), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_traffic_data_location', 'traffic_data', ['location'], unique=False, postgresql_using='gist')
    op.create_table('train_statuses',
    sa.Column('train_number', sa.String(length=20), nullable=True),
    sa.Column('train_name', sa.String(length=200), nullable=True),
    sa.Column('line_name', sa.String(length=100), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'on_time'"), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('stations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=2000), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('auth_provider_id', sa.String(length=500), nullable=True),
    sa.Column('password_hash', sa.String(length=500), nullable=True),
    sa.Column('home_zone_id', sa.UUID(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('reputation_score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['home_zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('weather_data',
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('rain', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), server_default=sa.text("'normal'"), nullable=False),
    sa.Column('hourly_forecast', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('daily_forecast', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alerts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_reports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), server_default=sa.text("'low'"), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ai_extracted_text', sa.Text(), nullable=True),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('media_type', sa.String(length=20), server_default=sa.text("'none'"), nullable=False),
    sa.Column('media_url', sa.String(length=2000), nullable=True),
    sa.Column('upvotes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('downvotes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('verification_status', sa.String(length=20), server_default=sa.text("'unverified'"), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_community_reports_location', 'community_reports', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_reports_search_vector', 'community_reports', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('user_interactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interactions_user_entity', 'user_interactions', ['user_id', 'entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interactions_user_entity', table_name='user_interactions')
    op.drop_table('user_interactions')
    op.drop_index('ix_reports_search_vector', table_name='community_reports', postgresql_using='gin')
    # op.drop_index('idx_community_reports_location', table_name='community_reports', postgresql_using='gist')
    op.drop_table('community_reports')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('train_statuses')
    # op.drop_index('idx_traffic_data_location', table_name='traffic_data', postgresql_using='gist')
    op.drop_table('traffic_data')
    op.drop_index('ix_social_mentions_search_vector', table_name='social_mentions', postgresql_using='gin')
    op.drop_table('social_mentions')
    op.drop_index('ix_news_search_vector', table_name='news_articles', postgresql_using='gin')
    op.drop_index('ix_news_city_published', table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_content_hash'), table_name='news_articles')
    # op.drop_index('idx_news_articles_location', table_name='news_articles', postgresql_using='gist')
    op.drop_table('news_articles')
    op.drop_index('ix_events_search_vector', table_name='events', postgresql_using='gin')
    # op.drop_index('idx_events_location', table_name='events', postgresql_using='gist')
    op.drop_table('events')
    op.drop_index('ix_city_summaries_city_generated', table_name='city_summaries')
    op.drop_table('city_summaries')
    op.drop_index(op.f('ix_zones_slug'), table_name='zones')
    op.drop_index('ix_zones_search_vector', table_name='zones', postgresql_using='gin')
    # op.drop_index('idx_zones_centroid', table_name='zones', postgresql_using='gist')
    # op.drop_index('idx_zones_boundary', table_name='zones', postgresql_using='gist')
    op.drop_table('zones')
    op.drop_index(op.f('ix_cities_slug'), table_name='cities')
    # op.drop_index('idx_cities_boundary', table_name='cities', postgresql_using='gist')
    op.drop_table('cities')
    # ### end Alembic commands ###
